### PR TITLE
Prototype

### LINKED ISSUE #24: Change result format
The current result is a JSON dictionary.  But the results are meant to be ordered by the elasticsearch match score.  So these should instead come back as a list.

### LINKED ISSUE #32: Make NR type-aware
When the UI is calling name-resolution, it frequently knows what type it wants.  Right now there is no ability to filter by type, so even if you know you want chemicals, you might get back a bunch of diseases.   Not only that, but NR doesn't even have the data to return for filtering, we make people go to NN to get the types.

Somehow we should probably bring type info into this.  I wonder if really all of NR should merge with NN in general...

@gaurav do you have any thoughts here?

See https://github.com/NCATSTranslator/Feedback/issues/42

### LINKED ISSUE #39: NameRes should allow filtering by biolink type
e.g. biolink:Disease

### LINKED ISSUE #43: Add the canonical label and Biolink type to NameRes results
At the moment, the Translator UI queries NameRes to find identifiers to display, then queries NodeNorm for the canonical label, Biolink type and other information. Both the canonical label and the Biolink type (as needed for #39 anyway) would be great to include in the NodeNorm results so that a second NodeNorm query is not needed.

### PR DESCRIPTION
**Pull request by cbizon**
Consumes the synonym files created by the synonym_prototype branch of Babel.

The input structure is now quite different.  Rather than a single document per (curie,label) pair, we now make one doc per curie.  We remove the id and length parameters, and add in biolink types and a preferred name.

This has an extra benefit of making the lookup code simpler, and reducing 3 solr calls to 1.

Fixes #39, fixes #43.
Fixes #24 by returning a list sorted by ElasticSearch scores instead of a dictionary.
Fixes #32 by adding types and canonical information to NameRes.

### CODE REVIEW

**Comment by cbizon** [comment]
It may not be worth reviewing yet @gaurav  - I realized that I need to update the openapi examples and the documentation.

**Comment by gaurav** [comment]
> It may not be worth reviewing yet @gaurav - I realized that I need to update the openapi examples and the documentation.

Sounds good! Let me know once this is ready for review.

**Comment by cbizon** [comment]
I think it is ready now - the docs will need to be updated for the load, but probably after the makefile is sorted, and I think the openapi doesn't have an example anyway.

**Comment by gaurav** [comment]
- [ ] Filtering by Biolink type doesn't seem to be working at the moment.

**Comment by gaurav** [comment]
@cbizon I've got this working now! I made some changes to the queries; could you please check them and make sure they still make sense? You can see all the changes made since your last commit by going here: https://github.com/TranslatorSRI/NameResolution/compare/48aa659000b04ded1721c8645113eebdf54963cf...prototype

I've left `preferred_name` as a `string` field for now, but I think we should change it into a `LowerTextField` so that we can boost results that include the query in the `preferred_name` as compared to the `names` list. What do you think?

Apart from that question, I'm good to merge!

**Review by gaurav — APPROVED** [review]
Works for me! (You can try it out at http://name-resolution-sri-dev.apps.renci.org/docs within the RENCI VPN).

**Comment by gaurav** [comment]
- [ ] Not all documents in Solr have a "names" key, so we should modify the code to handle the case where there is no "names" key in doc (e.g. on line 130 in server.py).

**Pull request merged**
